- hosts: azure_docker1
  tasks:

  - name: Create a portainer container
    docker_swarm_service:
      name: portainer
      image: portainer/portainer
      replicas: 2
      publish:
        - published_port: "4000"
          target_port: 9000
          protocol: tcp
          mode: host
      #volumes:
      #  - /data
      networks:
        - name: network_Orchestrator
          #ipv4_address: "10.174.0.3"


  - name: Create a Nextcloud container
    docker_swarm_service:
      name: Nextcloud
      image: nextcloud
      replicas: 2
      publish:
        - published_port: "4001"
          target_port: 80
          protocol: tcp
          mode: host
      #volumes:
      #  - /data
      networks:
        - name: network_Data
          #ipv4_address: "10.174.0.3"


  - name: Create a Redis container
    docker_swarm_service:
      name: Redis
      image: redis
      replicas: 2
      publish:
        - published_port: "4002"
          target_port: 6379
          protocol: tcp
          mode: host
      #volumes:
      #  - /data
      networks:
        - name: network_Orchestrator
          #ipv4_address: "10.174.0.3"


  - name: Create a nginx container
    docker_swarm_service:
      name: nginx
      image: nginx
      replicas: 2
      publish:
        - published_port: "4000"
          target_port: 80
          protocol: tcp
          mode: host
      #volumes:
      #  - /data
      networks:
        - name: network_Data
          #ipv4_address: "10.174.0.3"


  - name: Create a MediaWiki container
    docker_swarm_service:
      name: MediaWiki
      image: mediawiki
      replicas: 2
      publish:
        - published_port: "4003"
          target_port: 80
          protocol: tcp
          mode: host
      #volumes:
      #  - /data
      networks:
        - name: network_Data
          #ipv4_address: "10.174.0.3"
