
- hosts: zeus_project
  tasks:
  - name: Create a rancher container
    docker_container:
      name: rancher
      image: rancher/rancher
      ports:
        - "443:443"
      volumes:
        - /data
      networks:
        - name: network_Orchestrator
          ipv4_address: "10.174.0.2"
          aliases:
          - rancher
      purge_networks: yes

- hosts: zeus_project
  tasks:
  - name: Create a Nextcloud container
    docker_container:
      name: nextcloud
      image: nextcloud
      ports:
        - "4001:80"
      volumes:
        - /data
      networks:
        - name: network_Data
          ipv4_address: "10.172.0.2"
          aliases:
          - nextcloud
      purge_networks: yes
   
- hosts: zeus_project
  tasks:
  - name: Create a Redis container
    docker_container:
      name: BDD
      image: redis
      ports:
        - "4002:6379"
      volumes:
        - /data
      networks:
        - name: network_Data
          ipv4_address: "10.172.0.3"
          aliases:
          - redis
      purge_networks: yes
- hosts: zeus_project

  tasks:
  - name: Create a MediaWiki container
    docker_container:
      name: MediaWiki
      image: mediawiki
      ports:
        - "4003:80"
      volumes:
        - /data
      networks:
        - name: network_Data
          ipv4_address: "10.172.0.4"
          aliases:
          - mediawiki
      purge_networks: yes
