services:
  mybb:
    image: mybb/mybb:latest
    volumes:
    - ${HOME}/mybb:/var/www/html:rw
  nginx:
    image: nginx:mainline
    ports:
    - published: 80
      target: 80
    volumes:
    - ${HOME}/mybb:/usr/share/nginx/html
    - ${HOME}/nginx:/etc/nginx/conf.d
    links:
      - php
  php:
    image: php:7-fpm
    volumes:
    - ${HOME}/mybb:/usr/share/nginx/html
  postgresql:
    environment:
      POSTGRES_DB: mybb
      POSTGRES_PASSWORD: changeme
      POSTGRES_USER: mybb
    image: postgres:10.4
    volumes:
    - ${HOME}/postgres/data:/var/lib/postgresql/data:rw
version: '3.6'
